### PR TITLE
Include .zip archives in windows downloads dropdown

### PR DESCRIPTION
**Pull request by garazdawi**

### CODE REVIEW

**Comment by wojtekmach** [comment]
@garazdawi I noticed the test failure happens on master too, for some reason we generate time_correction.md link, not time_correction.**html**. I could see it in my ~/src/erlang-org master branch but could not reproduce it when running `make docs` in my ~/src/otp though. Perhaps it's due to old ex_doc version somehow or some docs misconfiguration?

**Comment by garazdawi** [comment]
Yea, I'm aware of that problem. Just haven't switched focus to it yet :)

**Comment by wojtekmach** [comment]
Right I guess what I was trying to say is I can help but I'd need some pointers (thought that might end up being more work for you sigh)

**Comment by garazdawi** [comment]
Much appriciated, but in this case there is nothing you can help with. The problem is that the source is broken: https://erlang.org/download/OTP-27.0.1.README.md

That .md is created by an internal script, so the solution is to fix the internal script. For 27.0.1 I can fix it my just updating the source README.md, but for all future releases I need to fix the internal script.

**Pull request merged**
